# Generated by Django 4.1.3 on 2022-12-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solucionario',
            name='id_ejercicio',
            field=models.CharField(max_length=200, verbose_name='id del ejercicio'),
        ),
        migrations.AlterModelTable(
            name='solucionario',
            table='solucionario_teclado',
        ),
    ]
