# Generated by Django 4.1.3 on 2022-12-23 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_solucionario_id_ejercicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='enunciado_solucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(blank=True, verbose_name='enunciado')),
                ('solucionario', models.TextField(blank=True, verbose_name='solucionario')),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.solucionario')),
            ],
            options={
                'verbose_name': 'Enunciado solucion',
                'db_table': 'Enunciado solucion tabla',
                'ordering': ['id'],
            },
        ),
    ]
